### ISSUE TITLE
borderRadius doesn't work on Android

### ISSUE THREAD

**Issue by dimaportenko** [dimaportenko/react-native-shadow-view#1]

**Comment by TommysG** [comment]
Amazing work. I don't know why this library doesn't have the appreciation needed. You are applying shadows on the native side for Android (which everyone wants) without using external libraries such as rn-svg etc. 
If you also add border radius to the View, then you have a completely native like iOS shadow on Android.  👏👏

**Comment by dimaportenko** [comment]
Solving the border radius issue wasn't as easy as I expected. I don't have the resources at this moment to investigate it. Have you tried https://github.com/ConduitMobileRND/react-native-simple-shadow-view? Maybe it's already doing what you need.

**Comment by TommysG** [comment]
Yeah I tried it, it has the same implementation but in Java. It has some problems with hot reload, for example you have to reload the app to apply some styles changes, but overall it has the same result. Thank you.

**Comment by dimaportenko** [comment]
Thank you for your feedback. I have an idea how to solve this issue, maybe I'll back to it at some point.

**Comment by dimaportenko** [comment]
@TommysG I actually play around a bit and make a solution for borderRadius. If you are going to try let me know if it works for you.

**Comment by TommysG** [comment]
Yes i tried it and it works fine. Thank you!!
