### ISSUE TITLE
Feature request: Inset Shadows

### ISSUE THREAD

**Issue by lukas-sl** [dimaportenko/react-native-shadow-view#7]
I'm currently using this package in a RN project and it has been a lifesaver after I experienced serious performance issues with another shadow package. So first of all, a huge thank you for the great work on the package! 👋

To completely implement the given design, however, I also need inset shadows. Is there any chance you could add this as a new feature?

**Comment by dimaportenko** [comment]
Hi @lukas-sl, glad this library was helpful for you. What are `inset shadows`?

**Comment by lukas-sl** [comment]
You can find an example [here](https://github.com/tokkozhin/react-native-neomorph-shadows#shadow--shadowflex). The first of the two images is a normal box shadow while the second one is an inset shadow, simulating that the element is inset (or pressed in) rather than elevated.

Unfortunately, I can't use the package I linked to as it doesn't support Expo at the moment.

**Comment by dimaportenko** [comment]
Oh, I see. Basically, it's not what I was trying to solve in the current library. And it also doesn't look like this feature can be simply added. Rather it requires building another library. 

Unfortunately the answer - It's not something I'm not going to work on here, at least in near future.

**Comment by lukas-sl** [comment]
Okay, I completely understand this decision. Thank you anyway for the quick response. 👍🏼

**Comment by dimaportenko** [comment]
Always welcome!
