### ISSUE TITLE
Avast mobile trojan detected

### ISSUE THREAD

**Issue by andrey-shostik** [dimaportenko/react-native-shadow-view#8]
Avast mobile detects trojan in my react native app when I add `react-native-shadow-view` to my package.json
https://www.virustotal.com/gui/file/f1b4465326fc4dad1b3aa37e67836fe288178a004797773d8944bc1c69894e9f?nocache=1

**Comment by dimaportenko** [comment]
hi @andrey-shostik, thanks for the report. 
I've just checked the app which includes this library and virustotal doesn't detect anything. Looks like this is not related to this library.
